<a href="https://colab.research.google.com/github/L16Aya/ap155_OUTPUTS/blob/main/155Lec_PS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Given matrix A and vector b
A = np.array([4., 4, 8, 4,
              4, 5, 3, 7,
              8, 3, 9, 9,
              4, 7, 9, 5]).reshape(4,4)
b = np.array([1., 2, 3, 4])

def gaussian_steps_no_pivot(A, b):
    A = A.copy().astype(float)
    b = b.copy().astype(float)
    n = len(b)

    steps = [(A.copy(), b.copy())]

    for k in range(n-1):
        for i in range(k+1, n):
            factor = A[i,k] / A[k,k]
            A[i,k:] -= factor * A[k,k:]
            b[i] -= factor * b[k]
        steps.append((A.copy(), b.copy()))

    return steps

def gaussian_steps_with_pivot(A, b):
    A = A.copy().astype(float)
    b = b.copy().astype(float)
    n = len(b)

    steps = [(A.copy(), b.copy())]

    for k in range(n-1):
        # Partial pivoting
        max_index = np.argmax(np.abs(A[k:,k])) + k
        if max_index != k:
            A[[k, max_index]] = A[[max_index, k]]
            b[[k, max_index]] = b[[max_index, k]]

        for i in range(k+1, n):
            factor = A[i,k] / A[k,k]
            A[i,k:] -= factor * A[k,k:]
            b[i] -= factor * b[k]
        steps.append((A.copy(), b.copy()))

    return steps

# Generate steps
steps_no_pivot = gaussian_steps_no_pivot(A, b)
steps_with_pivot = gaussian_steps_with_pivot(A, b)

# Display results
def print_steps(title, steps):
    print(title)
    for idx, (A_step, b_step) in enumerate(steps):
        aug = np.hstack([A_step, b_step.reshape(-1,1)])
        print(f"Step {idx} (Augmented [A|b]):\n{aug}\n")

print("Original Matrix A and b:\n", np.hstack([A, b.reshape(-1,1)]), "\n")

print_steps("Steps WITHOUT Pivoting:", steps_no_pivot)
print_steps("Steps WITH Pivoting:", steps_with_pivot)

Original Matrix A and b:
 [[4. 4. 8. 4. 1.]
 [4. 5. 3. 7. 2.]
 [8. 3. 9. 9. 3.]
 [4. 7. 9. 5. 4.]] 

Steps WITHOUT Pivoting:
Step 0 (Augmented [A|b]):
[[4. 4. 8. 4. 1.]
 [4. 5. 3. 7. 2.]
 [8. 3. 9. 9. 3.]
 [4. 7. 9. 5. 4.]]

Step 1 (Augmented [A|b]):
[[ 4.  4.  8.  4.  1.]
 [ 0.  1. -5.  3.  1.]
 [ 0. -5. -7.  1.  1.]
 [ 0.  3.  1.  1.  3.]]

Step 2 (Augmented [A|b]):
[[  4.   4.   8.   4.   1.]
 [  0.   1.  -5.   3.   1.]
 [  0.   0. -32.  16.   6.]
 [  0.   0.  16.  -8.   0.]]

Step 3 (Augmented [A|b]):
[[  4.   4.   8.   4.   1.]
 [  0.   1.  -5.   3.   1.]
 [  0.   0. -32.  16.   6.]
 [  0.   0.   0.   0.   3.]]

Steps WITH Pivoting:
Step 0 (Augmented [A|b]):
[[4. 4. 8. 4. 1.]
 [4. 5. 3. 7. 2.]
 [8. 3. 9. 9. 3.]
 [4. 7. 9. 5. 4.]]

Step 1 (Augmented [A|b]):
[[ 8.   3.   9.   9.   3. ]
 [ 0.   3.5 -1.5  2.5  0.5]
 [ 0.   2.5  3.5 -0.5 -0.5]
 [ 0.   5.5  4.5  0.5  2.5]]

Step 2 (Augmented [A|b]):
[[ 8.          3.          9.          9.          3.        ]
 [ 0.          5.5       

4.17 Pivoting usually helps because it avoids division by zero and makes elimination more stable, but in this matrix it cannot fix the deeper issue since the matrix is singular and has no unique solution. The determinant is zero, meaning the equations are dependent, so Gaussian elimination will always end with a row of zeros regardless of pivoting. Replacing a zero pivot with a very small number like 10⁻²⁰ does not actually solve the problem, it only hides the singularity and produces meaningless results instead of valid solutions.

In [1]:
import numpy as np

def jacobi_cyclic(n, max_iter=1000, tol=1e-5):
    # Matrix A (cyclic tridiagonal)
    A = np.zeros((n, n))
    for i in range(n):
        A[i, i] = 4
        if i > 0:
            A[i, i-1] = -1
        if i < n-1:
            A[i, i+1] = -1
    # Add cyclic connections
    A[0, n-1] = -1
    A[n-1, 0] = -1

    # b vector (all ones)
    b = np.ones(n)

    # Initial guess (all zeros)
    x = np.zeros(n)

    # For iteration
    x_new = np.zeros_like(x)

    for k in range(max_iter):
        for i in range(n):
            # Compute sum of neighbors, skipping diagonal
            s = 0
            for j in range(n):
                if j != i:
                    s += A[i, j] * x[j]
            x_new[i] = (b[i] - s) / A[i, i]

        # Check convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Converged after {k+1} iterations")
            return x_new

        # Update
        x[:] = x_new[:]

    print("Did not fully converge")
    return x_new

# Try for n=10 and n=20
sol10 = jacobi_cyclic(10)
sol20 = jacobi_cyclic(20)

print("Solution for n=10:\n", sol10)
print("\nSolution for n=20:\n", sol20)


Converged after 16 iterations
Converged after 16 iterations
Solution for n=10:
 [0.49999237 0.49999237 0.49999237 0.49999237 0.49999237 0.49999237
 0.49999237 0.49999237 0.49999237 0.49999237]

Solution for n=20:
 [0.49999237 0.49999237 0.49999237 0.49999237 0.49999237 0.49999237
 0.49999237 0.49999237 0.49999237 0.49999237 0.49999237 0.49999237
 0.49999237 0.49999237 0.49999237 0.49999237 0.49999237 0.49999237
 0.49999237 0.49999237]
