<a href="https://colab.research.google.com/github/L16Aya/ap155_OUTPUTS/blob/main/Sample_Kirchoff_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

V1 = 5.0
V2 = 10.0
R  = 1.0

K = np.array([
    [-R, -R,  0,  0],
    [ R,  0,  R,  0],
    [ 0,  R,  0,  R],
    [ 1, -1, -1,  1]
], dtype=float)

V = np.array([V1, -V2, V2, 0], dtype=float)

I = np.linalg.solve(K, V)
i1, i2, i3, i4 = I

I_R1 = i1
I_R2 = i2
I_R3 = i3
I_R4 = i4

I_from_V1 = -(i1 + i2)
R_eq = V1 / I_from_V1

print("=== Kirchhoff Matrix ===")
print(K)
print("\nVoltage Vector:", V)

print("\n=== Branch Currents ===")
print(f"R1 current = {I_R1:.3f} A")
print(f"R2 current = {I_R2:.3f} A")
print(f"R3 current = {I_R3:.3f} A")
print(f"R4 current = {I_R4:.3f} A")

print("\n=== Equivalent Resistance ===")
print(f"Total current drawn from V1 = {I_from_V1:.3f} A")
print(f"R_eq = {R_eq:.3f} ohm")

=== Kirchhoff Matrix ===
[[-1. -1.  0.  0.]
 [ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1. -1. -1.  1.]]

Voltage Vector: [  5. -10.  10.   0.]

=== Branch Currents ===
R1 current = -7.500 A
R2 current = 2.500 A
R3 current = -2.500 A
R4 current = 7.500 A

=== Equivalent Resistance ===
Total current drawn from V1 = 5.000 A
R_eq = 1.000 ohm
